apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name:  monolith-bank-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  monolith-bank-app-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
