apiVersion: v1
kind: Service
metadata:
  name: monolith-bank-app-service
spec:
  selector:
    app: java-monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
