apiVersion: v1
kind: Service
metadata:
  name: monolith-bank-app-service
spec:
  selector:
    app: java-monolith
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
